{% set version = "0.0.1" %}
# {% set git_server = "github.com" %}
{% set git_server = "services.pfem.clermont.inrae.fr/gitlab" %}
{% set git_group = "R-team" %}
{% set git_repo = "W4MRUtils" %}

package:
  name: r-w4mrutils
  version: "{{ version }}"

source:
  git_url: https://{{ git_server }}/{{ git_group }}/{{ git_repo }}.git
  git_rev: v{{ version }}
  git_depth: 1

build:
  noarch: generic
  merge_build_host: true
  number: 0
  script: R CMD INSTALL --build .

requirements:
  run:
    - r-base
  host:
    - r-base

test:
  commands:
    - R -e "library('W4MRUtils')"

about:
  home: https://github.com/workflow4metabolomics/W4MRUtils
  license: GNU AFFERO GENERAL PUBLIC LICENSE
  summary: 'Some utils tools for W4M'
  description: |
    Provides a set of utility function to prevent the spread of
    utilities script in W4M scripts, and centralize them in a package.
    Some are meant to be replaced by real packages in a near future, like
    the parse_args function: it is here only to prepare the ground for
    more global changes in W4M scripts and tools.
  dev_url: https://github.com/workflow4metabolomics/W4MRUtils
  doc_url: https://github.com/workflow4metabolomics/W4MRUtils
  doc_source_url: https://github.com/workflow4metabolomics/W4MRUtils/blob/v{{ version }}/README.md

extra:
  recipe-maintainers:
    - Lain-inrae
    - conda-forge/r